### ISSUE TITLE
The "HEROKU_" namespace is protected and shouldn't be used

### ISSUE THREAD

**Issue by FranciscoPinto** [raxod502/heroku-buildpack-git-lfs#2]
Thanks for the nice little buildpack! Would you consider changing the name of the repo var, though? Getting the following currently:

```
Setting HEROKU_BUILDPACK_GIT_LFS_REPO and restarting ⬢ some-app... done, v3
 ▸    Warning: The "HEROKU_" namespace is protected and shouldn't be used.
```

Cheers and thanks again!

**Comment by raxod502** [comment]
Seems reasonable. I would gladly accept a pull request.
