### ISSUE TITLE
How to set environment variable

### ISSUE THREAD

**Issue by wilbertaristo** [raxod502/heroku-buildpack-git-lfs#6]
I have created an `.env` file at the root directory which contains something like this:
`HEROKU_BUILDPACK_GIT_LFS_REPO=git@github.com:{GITHUB_USERNAME}/{GITHUB_REPO}.git`

However, when i try to deploy i keep getting this error message 
`Env var HEROKU_BUILDPACK_GIT_LFS_REPO is not set`

I am trying to deploy a simple Flask application. Any advice?

**Comment by wilbertaristo** [comment]
whoops nevermind i realized I had to add it to heroku config

**Comment by raxod502** [comment]
Clarified in the above-linked commit.
